name: New Interactive Scenario Lab Request
description: Create a new Interactive Scenario Lab for Microsoft Learn
title: "[NEW LAB]: "
labels: ["new-lab", "labs"]
assignees: []
body:
  # Lab Overview Section
  - type: input
    id: lab_title
    attributes:
      label: Lab Title
      description: Provide a clear, descriptive title for the new Interactive Scenario Lab
      placeholder: "e.g., AI Evaluation for Recipe Recommendation Systems"
    validations:
      required: true

  # Use Case Selection from fictional companies
  - type: dropdown
    id: use_case
    attributes:
      label: Business Use Case
      description: Select the fictional company and business scenario for this lab
      options:
        - "Adatum Corporation - Enterprise technology solutions and digital transformation"
        - "Adventure Works Cycles - Product recommendation and inventory management"
        - "Alpine Ski House - Seasonal demand planning and customer safety"
        - "Bellows College - Educational technology and student success analytics"
        - "Best For You Organics Company - Sustainable supply chain and quality assurance"
        - "Boulder Innovations - Research and development project management"
        - "Consolidated Messenger - Delivery route optimization and customer communication"
        - "Contoso, Ltd. - General business automation and productivity solutions"
        - "Contoso Pharmaceuticals - Drug discovery and clinical trial optimization"
        - "Contoso Suites - Hospitality management and guest experience optimization"
        - "Fabrikam, Inc. - Manufacturing process automation and quality control"
        - "Fabrikam Residences - Property management and resident services"
        - "First Up Consultants - Business consulting and client relationship management"
        - "Fourth Coffee - Customer experience optimization and loyalty programs"
        - "Graphic Design Institute - Creative workflow optimization and portfolio management"
        - "Humongous Insurance - Claims processing and risk assessment"
        - "Lakeshore Retail - Retail operations and customer analytics"
        - "Lamna Healthcare Company - Patient care optimization and medical data analysis"
        - "Liberty's Delightful Sinful Bakery & Cafe - Food service operations and recipe management"
        - "Lucerne Publishing - Content management and publication workflows"
        - "Margie's Travel - Travel recommendation and booking optimization"
        - "Munson's Pickles and Preserves Farm - Agricultural operations and recipe recommendation systems"
        - "Nod Publishers - Publishing and content distribution"
        - "Northwind Traders - Supply chain optimization and demand forecasting"
        - "Proseware, Inc. - Document management and workflow automation"
        - "Relecloud - Cloud infrastructure optimization and cost management"
        - "School of Fine Art - Educational content delivery and student portfolio management"
        - "Southridge Video - Media production and content management"
        - "Tailspin Toys - Product development and market analysis"
        - "Tailwind Traders - E-commerce personalization and fraud detection"
        - "The Phone Company - Telecommunications services and customer support"
        - "Trey Research - Scientific research and data analysis"
        - "VanArsdel, Ltd. - Enterprise software solutions and client management"
        - "Wide World Importers - International logistics and compliance management"
        - "Wingtip Toys - Toy manufacturing and safety compliance"
        - "Woodgrove Bank - Financial services automation and regulatory compliance"
        - "Woodgrove Groceries - Grocery operations and inventory management"
    validations:
      required: true

  # Learning Objectives
  - type: textarea
    id: learning_objectives
    attributes:
      label: Learning Objectives
      description: |
        List the key learning objectives for this lab. What should learners be able to do after completing this lab?
        
        **Examples:**
        - Identify relevant user needs for AI systems
        - Evaluate response quality using systematic criteria
        - Select appropriate evaluation metrics for business contexts
        - Apply evaluation frameworks for AI assessment
      placeholder: "Enter 3-5 specific learning objectives that align with the business scenario and target skills."
    validations:
      required: true

  # Task Configuration
  - type: markdown
    attributes:
      value: |
        ## Task Configuration
        Configure the main task for your Interactive Scenario Lab.

  - type: dropdown
    id: task_type
    attributes:
      label: Task Type
      description: Select the educational task type for this lab
      options:
        - "Multiple Choice (Single Answer) - Test factual knowledge or basic understanding"
        - "Multiple Select (Multiple Answers) - Assess broad conceptual knowledge or multi-step solutions"
        - "True/False (Binary Choice) - Quick check for understanding or common misconceptions"
        - "Fill-in-the-Blank (Cloze) - Test recall of specific terms or syntax"
        - "Matching (Pairing) - Assess recognition of relationships and concept mapping"
        - "Ordering (Sequencing) - Test understanding of processes or workflows"
        - "Classification (Grouping) - Check conceptual organization and categories"
        - "Hotspot (Image Selection) - Visual interaction for applied interface knowledge"
        - "Interactive Simulation (Configuration Adjustment) - Procedural knowledge and troubleshooting"
    validations:
      required: true

  - type: textarea
    id: task_description
    attributes:
      label: Task Description
      description: |
        Describe what learners will accomplish in this task and how it connects to the learning objectives.
        
        **Guidance**: Include context, the specific activity, and expected outcomes. Reference the examples at https://madiepev.github.io/mslearn-genai-interactive/recipe-chatbot-mockups/index.html
      placeholder: "Example: Learners will identify the 3 most relevant user needs from 9 options for the business scenario, developing skills in user-centered design and business requirement analysis."
    validations:
      required: true

  # Additional Context
  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes (Optional)
      description: |
        Include any additional context, requirements, or notes for lab development.
      placeholder: "e.g., Should highlight specific Microsoft products, target particular skill level, etc."

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Development Acknowledgment
      description: Please confirm understanding of the development process
      options:
        - label: "I understand this lab will be developed as standalone HTML assets and hosted via GitHub Pages"
          required: true
        - label: "I understand the lab should be completable in 30 minutes or less"
          required: true

# Workflow Comments:
# - lab_title: Used as base name for HTML files and repository structure  
# - use_case: Determines fictional company context and business scenario
# - learning_objectives: Defines the key skills and knowledge outcomes
# - task_type: Maps to specific HTML interaction templates and JavaScript behaviors
# - task_description: Becomes the main task content and instructions
# - additional_notes: Included in developer handoff documentation
#
# Labels "new-lab" and "labs" will trigger automated lab creation workflow